pipeline {
    agent { node { label 'agent1' } }
 options {
        //ansiColor('xterm')
        timeout(time: 1, unit: 'HOURS') 
    }
 environment {
    USER = 'sivamedam'
 }
    stages {
        stage('Init') {
            steps {
                sh '''
                    ls -ltrh
                    pwd
                    cd 01-vpc/
                    terraform init
                '''
            }
        }
        stage('Plan') {
            steps {
                sh '''
                   
                   ls -ltrh
                   pwd
                   cd 01-vpc/
                   terraform plan
                '''
            }
        }
        stage('Approval')
        {
            steps
            {
                input "Shall I Approve?"
            }
        }
        stage('Apply')
        {
            steps{
                sh '''
                pwd
                ls -ltrh
                cd 01-vpc
                terraform apply -auto-approve
                '''
            }
        }
    }
    post { 
        always { 
            echo 'I will always run wether job is success or not'
        }
        success{
            echo 'I will run only when job is success'
        }
        failure{
            echo 'I will run when job failure'
        }
    }
}